[package]
name = "svmvisor-emulator-driver-launcher"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[workspace]

[[bin]]
name = "BOOTX64"
path = "src/main.rs"
test = false
bench = false

[dependencies]
uefi = "=0.39.0"

[features]
no-authorization = []

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
