[workspace]
members = ["crates/dxe", "crates/hypervisor", "crates/m0b-probe", "tools/rompack"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
uefi = { version = "0.39.0", default-features = false }
x86_64 = { version = "0.15.5", default-features = false, features = ["instructions"] }

[profile.release]
panic = "abort"
