@{
    # Generated by new-candidate-pin.ps1 from a finished build-card.ps1 session.
    # Re-run it (not hand-editing) after every cargo xtask resident + build-card.
    # KnownWorking is the SHA-256 of the full 5 MiB currently on the card (learn it
    # with flash-card.ps1 -Action Backup -ConfirmFlash).
    Candidate     = 'target/firmware/card/native-resident/fb54e1a55d724622861595e7696e8511'
    ChildBytes    = 263168
    LoaderMode    = 'dev'
    ResidentBuild = 'target/card-dev/20260917T224621Z-4eb43992/resident'
    KnownWorking  = '07761f31e41e568bbb87bdf87b9a743b2ac1d63abb317959f76d3acce28676e5'
    Inputs = @(
        @{ Name = 'combined.bin'; Path = 'target/firmware/card/native-resident/fb54e1a55d724622861595e7696e8511/combined/combined-review.bin'; Bytes = 5242880; Hash = '07761f31e41e568bbb87bdf87b9a743b2ac1d63abb317959f76d3acce28676e5' }
        @{ Name = 'configuration.bin'; Path = 'target/firmware/card/native-resident/fb54e1a55d724622861595e7696e8511/svmvisor-endpoint.bin'; Bytes = 1502380; Hash = '6c0fc0f442ceac43c2c9338c4c85f7808cc2eed64a246d497255ef671427074a' }
        @{ Name = 'payload-slot.bin'; Path = 'target/firmware/card/native-resident/fb54e1a55d724622861595e7696e8511/combined/payload-slot.bin'; Bytes = 1048576; Hash = '518b87edefd8a420f65bf8f5112566f738f1f54ad77174a7b4b4d2633a5967fa' }
        @{ Name = 'pe-header.bin'; Path = 'target/firmware/card/native-resident/fb54e1a55d724622861595e7696e8511/combined/pe-header.bin'; Bytes = 128; Hash = '2904a5011a09d990fc624dd485644c6565e0066a97dc3e633fb44d94a36d70d7' }
        @{ Name = 'native-child.efi'; Path = 'target/firmware/card/native-resident/fb54e1a55d724622861595e7696e8511/reviewed-child.efi'; Bytes = 263168; Hash = 'ac29aef213eec9012893ade934c67340648cf9f6f40bfd4ad339eb062731c353' }
        @{ Name = 'candidate-manifest.json'; Path = 'target/firmware/card/native-resident/fb54e1a55d724622861595e7696e8511/manifest.json'; Bytes = 78839; Hash = '03eb2111e53881df57b02487ee292c9c05a2c6a670610c1b9667b1146f0b2c0e' }
        @{ Name = 'payload-manifest.json'; Path = 'target/firmware/card/native-resident/fb54e1a55d724622861595e7696e8511/combined/payload-manifest.json'; Bytes = 1307; Hash = 'a80e500481858f6a0e8eacf154a10a5ff270a4077340933830ad7ddd5b10b134' }
    )
}
