# Regenerate candidate-pin.psd1 from a finished build-card.ps1 session directory,
# computing every size and SHA-256 so re-baselining is one command, not hand
# editing. Offline only; never accesses hardware and never flashes.
#
#   .\firmware\card\new-candidate-pin.ps1 -CandidatePath <build-card session dir> -KnownWorking <64hex>
#
# -KnownWorking is the SHA-256 of the full 5 MiB currently installed on the card
# (learn it with `flash-card.ps1 -Action Backup -ConfirmFlash`). -OutFile writes
# elsewhere for review instead of overwriting the repository's candidate-pin.psd1.
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$CandidatePath,
    [Parameter(Mandatory)][ValidatePattern('^[0-9a-f]{64}$')][string]$KnownWorking,
    [string]$OutFile
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
. (Join-Path $PSScriptRoot 'card-validation.ps1')
. (Join-Path $PSScriptRoot 'card-full.ps1')
if (-not $OutFile) { $OutFile=Join-Path $PSScriptRoot 'candidate-pin.psd1' }

$candidateFull=(Resolve-Path -LiteralPath $CandidatePath).Path
$rootPrefix=$root.TrimEnd('\','/')+[IO.Path]::DirectorySeparatorChar
if (-not $candidateFull.StartsWith($rootPrefix,[StringComparison]::OrdinalIgnoreCase)) { throw 'CandidatePath must be inside the repository.' }
function To-RepoRelative([string]$Full) {
    $resolved=[IO.Path]::GetFullPath($Full)
    if (-not $resolved.StartsWith($rootPrefix,[StringComparison]::OrdinalIgnoreCase)) { throw "Path escapes the repository: $Full" }
    return $resolved.Substring($rootPrefix.Length).Replace('\','/')
}

$manifestPath=Join-Path $candidateFull 'manifest.json'
if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) { throw "Not a build-card session: manifest.json missing in $candidateFull" }
$manifest=Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json
if ($manifest.status -cne 'built_review_required') { throw "Candidate manifest status is '$($manifest.status)', not 'built_review_required'." }
foreach ($field in @('loader_mode','combined_sha256','combined_bytes','payload_sha256')) {
    if ($null -eq $manifest.PSObject.Properties[$field] -or $null -eq $manifest.$field) { throw "Candidate manifest lacks required field: $field (was the combined image built with -BuildFpga?)" }
}
$loaderMode=[string]$manifest.loader_mode
$null=Get-CardFeatureForMode $loaderMode
if (-not $manifest.resident_build_path) { throw 'Candidate manifest lacks resident_build_path.' }
$residentRelative=To-RepoRelative ([string]$manifest.resident_build_path)

# Name -> file inside the build-card session. These are exactly the files the
# full path stages and checks; the layout self-consistency is re-proven below.
$inputMap=[ordered]@{
    'combined.bin'           = 'combined/combined-review.bin'
    'configuration.bin'      = 'svmvisor-endpoint.bin'
    'payload-slot.bin'       = 'combined/payload-slot.bin'
    'pe-header.bin'          = 'combined/pe-header.bin'
    'native-child.efi'       = 'reviewed-child.efi'
    'candidate-manifest.json'= 'manifest.json'
    'payload-manifest.json'  = 'combined/payload-manifest.json'
}
$inputs=@()
foreach ($name in $inputMap.Keys) {
    $file=Join-Path $candidateFull $inputMap[$name]
    if (-not (Test-Path -LiteralPath $file -PathType Leaf)) { throw "Candidate is missing $name ($($inputMap[$name]))." }
    $item=Get-Item -LiteralPath $file
    $inputs+=@{Name=$name;Path=(To-RepoRelative $file);Bytes=[long]$item.Length;Hash=(Get-CardReturningHash $file)}
}
$childBytes=[long]((Get-Item -LiteralPath (Join-Path $candidateFull 'reviewed-child.efi')).Length)

$pin=[ordered]@{
    Candidate     = (To-RepoRelative $candidateFull)
    ChildBytes    = $childBytes
    LoaderMode    = $loaderMode
    ResidentBuild = $residentRelative
    KnownWorking  = $KnownWorking
    Inputs        = $inputs
}
# Validate the generated pin exactly as flash-card.ps1 will before writing it.
$verify=@{Candidate=$pin.Candidate;ChildBytes=$pin.ChildBytes;LoaderMode=$pin.LoaderMode;ResidentBuild=$pin.ResidentBuild;KnownWorking=$pin.KnownWorking;Inputs=$pin.Inputs}
Assert-CardCandidatePin $verify $root

$eol="`r`n"
$builder=[Text.StringBuilder]::new()
$null=$builder.Append("@{$eol")
$null=$builder.Append("    # Generated by new-candidate-pin.ps1 from a finished build-card.ps1 session.$eol")
$null=$builder.Append("    # Re-run it (not hand-editing) after every cargo xtask resident + build-card.$eol")
$null=$builder.Append("    # KnownWorking is the SHA-256 of the full 5 MiB currently on the card (learn it$eol")
$null=$builder.Append("    # with flash-card.ps1 -Action Backup -ConfirmFlash).$eol")
$null=$builder.Append("    Candidate     = '$($pin.Candidate)'$eol")
$null=$builder.Append("    ChildBytes    = $($pin.ChildBytes)$eol")
$null=$builder.Append("    LoaderMode    = '$($pin.LoaderMode)'$eol")
$null=$builder.Append("    ResidentBuild = '$($pin.ResidentBuild)'$eol")
$null=$builder.Append("    KnownWorking  = '$($pin.KnownWorking)'$eol")
$null=$builder.Append("    Inputs = @($eol")
foreach ($entry in $pin.Inputs) {
    $null=$builder.Append("        @{ Name = '$($entry.Name)'; Path = '$($entry.Path)'; Bytes = $($entry.Bytes); Hash = '$($entry.Hash)' }$eol")
}
$null=$builder.Append("    )$eol")
$null=$builder.Append("}$eol")
[IO.File]::WriteAllText($OutFile,$builder.ToString(),[Text.UTF8Encoding]::new($false))
# Confirm the written file parses and re-validates.
$written=Import-PowerShellDataFile -LiteralPath $OutFile
Assert-CardCandidatePin $written $root
Write-Output "Wrote candidate-pin ($loaderMode loader, child $childBytes bytes): $OutFile"
Write-Output "  KnownWorking = $KnownWorking"
